apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    tier: frontend
  namespace: dev
  annonatations:
    buildVersion: v1
spec:
  replicas: 6
  template:
    metadata:
       name: myapp-pod
       labels:
        app: myapp
        tier: frontend
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 6379
          resources:
              requests:
                  memory: "1G"
                  cpu: 1
              limits:
                  memory: "2G"
                  cpu: 2
          command: ["sleep2.0"] 
          args: ["10"]
          envFrom:
              - configMapFrom:
                  name: app-config
                  secretRef:
                  name: app-secret
  selector:
    withLabels:
      app: myapp
      tier: frontend
