apiVersion: v1
kind: Config
clusters:
  - name: my-kube-playground
    certificate-authority: /etc/kubernetes/pki/ca/crt
    server: https://my-kube-playground:6443
users:
    - name: my-kube-admin
      user:
        client-certificate: admin.crt
        client-key: admin.key

context:
  - name: my-kube-admin@my-kube-playground
    context:
      cluster: my-kube-playground
      user: my-kube-admin
      namespace: finance