apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: monitoring-daemon
spec:
  selector:
      matchLabels: monitoring-agent
  template:
    metadata:
      labels:
        app: monitoring-agent
    spec:
      containers:
        - name: container-agent
          image: container-agent
